### ISSUE TITLE
Add `babel-preset` to the repository's topics

### ISSUE THREAD

**Issue by marcusrbrown** [americanexpress/babel-preset-amex#47]
While researching other Babel config presets, I noted that several projects include a repo topic of `babel-preset`. I believe adding that topic could improve the project's discoverability in GitHub. It may also be prudent to sync those topics with the keywords list in `package.json`. 

I don't have sufficient permissions to add the topic myself. 🤙🏽

**Comment by 10xLaCroixDrinker** [comment]
Done 👍

**Comment by 10xLaCroixDrinker** [comment]
I've added the topic. Feel free to open the PR for the package.json keywords. Otherwise, let's close this issue.
